spring:
    data:
        mongodb:
            uri: mongodb+srv://${USERNAME}:${PASSWORD}@shopify-monitor-cluster.qhcpxbr.mongodb.net/
            database: ${DB}

logging:
    level:
        com.shopify.monitor.shopifymonitor: INFO

site:
    urls:
        - https://undefeated.com
        #- https://atmosusa.com