spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: shopify

logging:
    level:
        com.shopify.monitor.shopifymonitor: DEBUG


shopify:
    site-url:
        undefeated: "https://undefeated.com"

site:
    urls:
        - https://undefeated.com

#shopify:
#    undefeated:
#        url: "https://undefeated.com"
#    kith:
#        url: "https://kith.com"
#    supreme:
#        url: "https://us.supreme.com"