spring:
    data:
        mongodb:
            uri: ${MONGO_URI}
            database: ${DB}

logging:
    level:
        com.shopify.monitor.shopifymonitor: INFO

site:
    urls:
        - https://undefeated.com
#        - https://atmosusa.com
#        - https://kith.com